import os
import sys
import json
import joblib
import pickle
import numpy as np

# Include src directory in python path
sys.path.append(os.path.dirname(__file__))

# Compatibility wrapper for legacy scikit-learn unpickling
import sklearn.linear_model
sys.modules['sklearn.linear_model.logistic'] = sklearn.linear_model

from preprocess import clean_text, META_BLOCKLIST

def export_models():
    base_dir = os.path.dirname(os.path.dirname(__file__))
    models_dir = os.path.join(base_dir, "models")
    js_output_path = os.path.join(base_dir, "static", "js", "model_data.js")

    model_a_path = os.path.join(models_dir, "fake_news_model.pkl")
    vectorizer_a_path = os.path.join(models_dir, "tfidf_vectorizer.pkl")
    model_b_path = os.path.join(models_dir, "liar_model.sav")

    print("Loading Model A...")
    model_a = joblib.load(model_a_path)
    vectorizer_a = joblib.load(vectorizer_a_path)

    vocab_a = vectorizer_a.vocabulary_
    idf_a = vectorizer_a.idf_
    coef_a = model_a.coef_[0]
    intercept_a = float(model_a.intercept_[0])

    inv_vocab_a = {v: k for k, v in vocab_a.items()}

    # Select top informative features to keep JS bundle fast and lightweight (~3500 features)
    abs_coef_a = np.abs(coef_a)
    top_indices_a = np.argsort(abs_coef_a)[-3500:]

    weights_a = {}
    idf_dict_a = {}
    for idx in top_indices_a:
        term = inv_vocab_a[idx]
        weights_a[term] = float(coef_a[idx])
        idf_dict_a[term] = float(idf_a[idx])

    # Also include META_BLOCKLIST words explicitly if present
    for w in META_BLOCKLIST:
        if w in vocab_a:
            idx = vocab_a[w]
            weights_a[w] = float(coef_a[idx])
            idf_dict_a[w] = float(idf_a[idx])

    data_a = {
        "intercept": intercept_a,
        "weights": weights_a,
        "idf": idf_dict_a,
        "norm": vectorizer_a.norm if hasattr(vectorizer_a, 'norm') else "l2",
        "sublinear_tf": getattr(vectorizer_a, 'sublinear_tf', True)
    }

    # Process Model B (LIAR Statement Classifier) if available
    data_b = None
    if os.path.exists(model_b_path):
        print("Loading Model B (LIAR Statement Classifier)...")
        try:
            with open(model_b_path, "rb") as f:
                model_b = pickle.load(f)
            vec_b = model_b.named_steps['LogR_tfidf']
            clf_b = model_b.named_steps['LogR_clf']

            vocab_b = vec_b.vocabulary_
            idf_b = vec_b.idf_
            coef_b = clf_b.coef_[0]
            intercept_b = float(clf_b.intercept_[0])
            inv_vocab_b = {v: k for k, v in vocab_b.items()}

            abs_coef_b = np.abs(coef_b)
            top_indices_b = np.argsort(abs_coef_b)[-3500:]

            weights_b = {}
            idf_dict_b = {}
            for idx in top_indices_b:
                term = inv_vocab_b[idx]
                weights_b[term] = float(coef_b[idx])
                idf_dict_b[term] = float(idf_b[idx])

            data_b = {
                "intercept": intercept_b,
                "weights": weights_b,
                "idf": idf_dict_b,
                "norm": vec_b.norm if hasattr(vec_b, 'norm') else "l2",
                "sublinear_tf": getattr(vec_b, 'sublinear_tf', True)
            }
        except Exception as e:
            print(f"Warning: Could not export Model B: {e}")

    # Output JS file
    js_content = f"""/**
 * VeritasAI — Pre-computed TF-IDF & Logistic Regression Model Weights
 * Auto-generated by src/export_model_to_js.py for Client-Side ML Inference on GitHub Pages.
 */
window.VERITAS_MODEL_A = {json.dumps(data_a, indent=2)};
window.VERITAS_MODEL_B = {json.dumps(data_b, indent=2) if data_b else 'null'};
"""

    os.makedirs(os.path.dirname(js_output_path), exist_ok=True)
    with open(js_output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Successfully exported model weights to {js_output_path} ({len(weights_a)} Model A features, {len(weights_b) if data_b else 0} Model B features).")

if __name__ == "__main__":
    export_models()
